server:
  port: 9091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/STS-ProductStockServiceDb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true

myapplication:
  product-service:
    feign-client: http://localhost:9090/api/v.0.1
  stock-service:
    feign-client: http://localhost:9091/api/v.0.1